apiVersion: v1
kind: ConfigMap
metadata:
    name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8"
  database: "msvc_usuarios"
  username: "root"
  password: "1234"
  cursos_url: "msvc-cursos:8002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres14"
  database: "msvc_cursos"
  username: "postgres"
  password: "1234"
  usuarios_url: "msvc-usuarios:8001"