apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - image: horaciosalva/cursos:latest
          name: msvc-cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: "postgres14"
            - name: DB_DATABASE
              value: "msvc_cursos"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234"
            - name: USUARIOS_URL
              value: "msvc-usuarios:8001"