apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres14
spec:
    replicas: 1
    selector:
        matchLabels:
            role: postgres
    template:
        metadata:
            labels:
                role: postgres
        spec:
            containers:
                - image: postgres:14-alpine
                  name: postgres14
                  ports:
                    - containerPort: 5432
                  env:
                    - name: POSTGRES_PASSWORD
                      value: "1234"
                    - name: POSTGRES_DB
                      value: "msvc_cursos"
                  volumeMounts:
                      - name: data-postgres
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: data-postgres
                  persistentVolumeClaim:
                      claimName: postgres-pvc
