
services:

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: msvc_cursos
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - curso_kubernetes

  msvc-cursos:
    container_name: msvc-cursos
    image: horaciosalva/cursos
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: ec2-52-90-78-197.compute-1.amazonaws.com:8001
    networks:
      - curso_kubernetes
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data_postgres:
    name: data_postgres

networks:
  curso_kubernetes:
    name: curso_kubernetes