
services:

  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - curso_kubernetes

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: msvc_cursos
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - curso_kubernetes

  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - curso_kubernetes
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - curso_kubernetes
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data_mysql:
    name: data_mysql
  data_postgres:
    name: data_postgres

networks:
  curso_kubernetes:
    name: curso_kubernetes