server:
    port: 8002

spring:
  application:
    name: msvc-cursos

  datasource:
    url: jdbc:postgresql://localhost:5432/msvc_cursos
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: DEBUG