server:
  port: ${PORT:8001}

#msvc:
  #cursos:
    #url: ${CURSOS_URL:msvc-cursos:8002}

spring:
  application:
    name: msvc-usuarios

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8}:3306/${DB_DATABASE:msvc_usuarios}?serverTimezone=America/Buenos_Aires&allowPublicKeyRetrieval=false
    username: ${DB_USERNAME:root}
    #password: My$tr0ngP@ssw0rd!
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: /app/logs