server:
  port: ${PORT:8001}

spring:
  application:
    name: msvc-usuarios

  datasource:
    url: jdbc:mysql://mysql8:3306/msvc_usuarios?serverTimezone=America/Buenos_Aires&allowPublicKeyRetrieval=false
    username: root
    #password: My$tr0ngP@ssw0rd!
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: /app/logs